### ISSUE TITLE
Issue with compilation on <=IE7

### ISSUE THREAD

**Issue by u01jmg3** [hashchange/jquery.documentsize#2]
I know support is listed as `>=IE8` but is there any way of solving the compilation error you get with `IE6/7`? On page load I get a `type mismatch` error refering to [`document.body.removeChild( iframe );`](https://github.com/hashchange/jquery.documentsize/blob/da8dea441975a1a86a4b6218217567e0f6d14ee6/dist/jquery.documentsize.js#L433) within [`testDocumentScroll()`](https://github.com/hashchange/jquery.documentsize/blob/da8dea441975a1a86a4b6218217567e0f6d14ee6/dist/jquery.documentsize.js#L403-L435)?

Could a check be incorporated to subvert the error?

Thanks

**Comment by hashchange** [comment]
I have added a try-catch around critical parts. Unsupported browsers also get a fallback solution for the document size, which is identical to the way jQuery calculates it (or rather, guesses it).

I don't know if that is enough to make things work in IE6 and IE7 specifically. Let me know if you still run into trouble, and I'll see what I can do. I won't support these browsers, but if there is an easy fix without introducing a lot of overhead, then why not do it.

**Comment by u01jmg3** [comment]
Thanks for your speed in sorting this. Unfortunately, IE6/7 are still complaining about [`document.body.removeChild( iframe );`](https://github.com/hashchange/jquery.documentsize/blob/547bab00e37d6af282d292fc2527f93b28082dd3/dist/jquery.documentsize.js#L461) and a type mismatch

<img width="589" alt="error" src="https://cloud.githubusercontent.com/assets/1266205/12677418/d45fee58-c690-11e5-8737-4639ebcfe0a9.png">

**Comment by hashchange** [comment]
Fixed it now ;) The error is gone. The fix will land in the next release.

That said, IE6 and IE 7 are still not supported properly. The feature test works, but the result is not ideal. IE6/7 seem to detect body size, rather than document size.

There is an easy workaround, though, which you can use in your own code. If you have jQuery in place, you just have to detect IE < 8 in [one way or another](https://msdn.microsoft.com/en-us/library/ms537509(v=vs.85).aspx). Then, all you need is a wrapper along the lines of 

    function documentWidth () {
        return isAncientIE ? $( document ).width() : $.documentWidth();
    }

In case you don't use a DOM library, you can replace the `$( document ).width()` call with a few lines from the [`guessDocumentSize` fallback](https://github.com/hashchange/jquery.documentsize/blob/300380cece6104ffd21921efa184f784e594c7eb/src/jquery.documentsize.js#L547-L565). It does the exact same thing that jQuery does.

**Comment by u01jmg3** [comment]
Thanks! :)

When will the next release be released?

I'm using [Detectizr](https://github.com/barisaydinoglu/Detectizr) to detect IE6/7. Appreciate the code suggestions.

**Comment by hashchange** [comment]
As soon as I have figured out #3 ;)

**Comment by hashchange** [comment]
Has landed in version 1.2.3.

**Comment by u01jmg3** [comment]
Just to clarify, I can confirm the IE6/7 compilation error has gone!
