### ISSUE TITLE
changing visual viewport by code

### ISSUE THREAD

**Issue by AliBahramiEhsan** [hashchange/jquery.documentsize#4]
Is there a way to change visual viewport by code?
Thanks

**Comment by hashchange** [comment]
Not that I am aware of. Perhaps you can give it a shot on Stack Overflow, but I wouldn't be too optimistic. 

(If you find out about a method that works, it would be great if you can drop me a line here. I don't have tests in place for `pinchZoomFactor()` for exactly that reason, and I'd probably add a few if there were a way to pinch-zoom programmatically.)

**Comment by hashchange** [comment]
It seems my former self knew more about it than my current self ;) Turns out it is possible after all, and it is in fact used in the test suite. [I've just come across the code](https://github.com/hashchange/jquery.documentsize/blob/5536cd8812c34195cb5b250a1cfc53e67faa72aa/spec/helpers/dom-utils.js#L265-L360). I'd assume `setMetaViewportZoom()` is the function you are looking for. Feel free to copy and use it as you like.
