### ISSUE TITLE
Remove `document.write`

### ISSUE THREAD

**Issue by proimage** [hashchange/jquery.documentsize#8]
I'm getting a warning in web.dev & Chrome, caused by this library using `document.write`:

https://developers.google.com/web/updates/2016/08/removing-document-write

**Comment by regiside** [comment]
Same, I wonder if it's needed. Looking through the code now.

**Comment by hashchange** [comment]
Sorry for having you kept waiting for so long. It seems that the alert is misplaced. It is supposed to warn you that `document.write` is used for injecting a script, which would prevent the page from being rendered until the script arrives.

According to the docs, the warning should be [limited to an injection in the top-level document](https://developer.chrome.com/blog/removing-document-write/#:~:text=The%20document.write()%20is%20in%20a%20top%20level%20document.%20The%20intervention%20does%20not%20apply%20to%20document.written%20scripts%20within%20iframes%20as%20they%20don%27t%20block%20the%20rendering%20of%20the%20main%20page.). In an iframe, script injections don't matter because they don't affect the rendering of the main document.

This is what actually happens: The [offending line](https://github.com/hashchange/jquery.documentsize/blob/4f9c24f054f604b165082bbe5b3b424ad042a729/src/jquery.documentsize.js#L496) injects some HTML locally as part of a test, doesn't download a thing, and to top it all off, the HTML is even created inside an iframe.

So there are several independent reasons why the warning shouldn't be triggered. The problem it is supposed to address doesn't exist. I guess we are dealing with a Chrom bug here. And it is safe to ignore the message.
